// src/components/LexicalRenderer.tsx
import { RichText } from '@payloadcms/richtext-lexical/react'
import type { SerializedEditorState } from '@payloadcms/richtext-lexical/lexical'

interface LexicalRendererProps {
  data: SerializedEditorState | any | null | undefined
}

/**
 * Enterprise Component: LexicalRenderer
 * Purpose: Safely serializes Payload CMS Lexical JSON into native React Server Components.
 * Security: Prevents XSS by avoiding dangerouslySetInnerHTML.
 */
export const LexicalRenderer = ({ data }: LexicalRendererProps) => {
  if (!data) return null

  return (
    // The 'prose' class from Tailwind Typography plugin automatically styles the HTML
    // (headings, lists, bold text) generated by the Lexical serializer.
    // Ensure @tailwindcss/typography is installed and added to tailwind.config.ts
    <div className="prose prose-blue max-w-none prose-headings:font-bold prose-a:text-blue-600 hover:prose-a:text-blue-800">
      <RichText data={data} />
    </div>
  )
}