/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'backend-roles': BackendRole;
    specialties: Specialty;
    doctors: Doctor;
    certificates: Certificate;
    facilities: Facility;
    institutions: Institution;
    leads: Lead;
    'lead-files': LeadFile;
    procedures: Procedure;
    'doctors-media': DoctorsMedia;
    'facilities-media': FacilitiesMedia;
    'institutions-media': InstitutionsMedia;
    'certificates-media': CertificatesMedia;
    'procedures-media': ProceduresMedia;
    'medical-assets': MedicalAsset;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'backend-roles': BackendRolesSelect<false> | BackendRolesSelect<true>;
    specialties: SpecialtiesSelect<false> | SpecialtiesSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    facilities: FacilitiesSelect<false> | FacilitiesSelect<true>;
    institutions: InstitutionsSelect<false> | InstitutionsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'lead-files': LeadFilesSelect<false> | LeadFilesSelect<true>;
    procedures: ProceduresSelect<false> | ProceduresSelect<true>;
    'doctors-media': DoctorsMediaSelect<false> | DoctorsMediaSelect<true>;
    'facilities-media': FacilitiesMediaSelect<false> | FacilitiesMediaSelect<true>;
    'institutions-media': InstitutionsMediaSelect<false> | InstitutionsMediaSelect<true>;
    'certificates-media': CertificatesMediaSelect<false> | CertificatesMediaSelect<true>;
    'procedures-media': ProceduresMediaSelect<false> | ProceduresMediaSelect<true>;
    'medical-assets': MedicalAssetsSelect<false> | MedicalAssetsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'patient-journey': PatientJourney;
    'why-queretaro': WhyQueretaro;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'patient-journey': PatientJourneySelect<false> | PatientJourneySelect<true>;
    'why-queretaro': WhyQueretaroSelect<false> | WhyQueretaroSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The Admin option is the principal administrator role and can create backend roles.
   */
  roles: ('admin' | 'doctor' | 'patient')[];
  /**
   * Configurable backend permissions. Only the principal admin can assign these roles.
   */
  backendRoles?: (number | BackendRole)[] | null;
  fullName: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backend-roles".
 */
export interface BackendRole {
  id: number;
  name: string;
  /**
   * Internal identifier, for example lead-coordinator or content-editor.
   */
  slug: string;
  description?: string | null;
  isActive?: boolean | null;
  permissions: {
    target:
      | 'users'
      | 'backend-roles'
      | 'specialties'
      | 'doctors'
      | 'certificates'
      | 'facilities'
      | 'institutions'
      | 'leads'
      | 'lead-files'
      | 'procedures'
      | 'doctors-media'
      | 'facilities-media'
      | 'institutions-media'
      | 'certificates-media'
      | 'procedures-media'
      | 'medical-assets'
      | 'site-settings'
      | 'patient-journey'
      | 'why-queretaro';
    read?: boolean | null;
    create?: boolean | null;
    update?: boolean | null;
    delete?: boolean | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialties".
 */
export interface Specialty {
  id: number;
  title: string;
  slug: string;
  /**
   * Brief description of the specialty for the category landing page.
   */
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  fullName: string;
  slug: string;
  medicalLicense?: string | null;
  /**
   * Primary headshot for directory cards.
   */
  profilePicture: number | DoctorsMedia;
  /**
   * Photos of the doctor's office or consultation rooms.
   */
  officeGallery?: (number | DoctorsMedia)[] | null;
  specialties?: (number | Specialty)[] | null;
  /**
   * Select the specific procedures this doctor is authorized to perform.
   */
  procedures?: (number | Procedure)[] | null;
  /**
   * Hospitals or clinics where this specialist attends patients.
   */
  facilities?: (number | Facility)[] | null;
  biography?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional hero background image for the public doctor profile.
   */
  heroBackground?: (number | null) | DoctorsMedia;
  /**
   * Optional direct MP4/WebM URL for the hero background. If present, it overrides the hero image.
   */
  heroVideoUrl?: string | null;
  /**
   * Procedure, technology, OR or treatment images/videos shown as a clinical gallery on the doctor profile.
   */
  procedureGallery?: (number | DoctorsMedia)[] | null;
  /**
   * External YouTube, Vimeo or public video URLs shown inside the procedure gallery.
   */
  procedureVideoLinks?:
    | {
        title: string;
        url: string;
        caption?: string | null;
        /**
         * Optional image thumbnail for this external procedure video.
         */
        thumbnail?: (number | null) | DoctorsMedia;
        id?: string | null;
      }[]
    | null;
  patientTestimonials?:
    | {
        title: string;
        /**
         * YouTube, Vimeo or direct hosted video URL.
         */
        videoUrl: string;
        /**
         * Example: Dallas, Texas or Phoenix, Arizona.
         */
        patientLocation?: string | null;
        quote?: string | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  phone?: string | null;
  email?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images and short videos used for doctor portraits, clinical galleries, and profile backgrounds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors-media".
 */
export interface DoctorsMedia {
  id: number;
  /**
   * Crucial for SEO and Accessibility. Describe the image content.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procedures".
 */
export interface Procedure {
  id: number;
  name: string;
  slug: string;
  specialty: number | Specialty;
  coverImage?: (number | null) | ProceduresMedia;
  /**
   * Used for procedure cards and SEO Meta Description (Max 160 chars).
   */
  shortSummary: string;
  fullDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  pricing: {
    /**
     * Numeric value for sorting/filtering. Displayed in USD.
     */
    startingPriceUSD: number;
    financingAvailable?: boolean | null;
  };
  /**
   * e.g., "1 to 2 weeks"
   */
  recoveryTime: string;
  /**
   * e.g., "2 to 3 hours"
   */
  surgeryDuration: string;
  anesthesiaType?: ('general' | 'local_sedation' | 'local') | null;
  /**
   * Images or uploaded videos shown in the public procedure gallery.
   */
  procedureGallery?: (number | ProceduresMedia)[] | null;
  /**
   * External YouTube, Vimeo or public video URLs shown inside the procedure gallery.
   */
  procedureVideoLinks?:
    | {
        title: string;
        url: string;
        caption?: string | null;
        /**
         * Optional image thumbnail for this external procedure video.
         */
        thumbnail?: (number | null) | ProceduresMedia;
        id?: string | null;
      }[]
    | null;
  /**
   * Provide common questions regarding this medical procedure.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images and short videos used for procedure covers and media galleries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procedures-media".
 */
export interface ProceduresMedia {
  id: number;
  /**
   * Crucial for SEO and Accessibility. Describe the image content.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities".
 */
export interface Facility {
  id: number;
  name: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Location city.
   */
  city: string;
  specialtiesOffered: (number | Specialty)[];
  /**
   * List of specialists practicing at this facility.
   */
  doctors?: (number | Doctor)[] | null;
  accreditations?: (number | Certificate)[] | null;
  /**
   * Main uploaded image or video used as the facility hero background. Images are also used for cards and SEO previews.
   */
  heroImage: number | FacilitiesMedia;
  /**
   * Optional YouTube, Vimeo or direct MP4/WebM URL for the hero background. If filled, it takes priority over the uploaded hero media.
   */
  heroVideoUrl?: string | null;
  /**
   * Showcase photos or uploaded videos of rooms, equipment and patient areas.
   */
  infrastructureGallery?: (number | FacilitiesMedia)[] | null;
  /**
   * External video links shown inside the facility gallery. Use this for YouTube, Vimeo, Instagram or other public video URLs.
   */
  infrastructureVideoLinks?:
    | {
        title: string;
        url: string;
        caption?: string | null;
        /**
         * Optional image thumbnail for this external video link.
         */
        thumbnail?: (number | null) | FacilitiesMedia;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  /**
   * e.g., Board Certified Plastic Surgeon, Joint Commission International.
   */
  name: string;
  /**
   * Entity that granted the certificate (e.g., Consejo Mexicano de Cirugía Plástica).
   */
  issuer: string;
  /**
   * Public link to verify this accreditation online.
   */
  verificationUrl?: string | null;
  logo: number | CertificatesMedia;
  /**
   * Uncheck to hide this certificate from the frontend without deleting it.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates-media".
 */
export interface CertificatesMedia {
  id: number;
  /**
   * Crucial for SEO and Accessibility. Describe the image content.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Images and short videos used for facility hero backgrounds and galleries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities-media".
 */
export interface FacilitiesMedia {
  id: number;
  /**
   * Crucial for SEO and Accessibility. Describe the image content.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions".
 */
export interface Institution {
  id: number;
  /**
   * The official name of the medical network or institution.
   */
  name: string;
  slug: string;
  /**
   * Detailed content for the institution landing page. Crucial for SEO.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  logo: number | InstitutionsMedia;
  /**
   * Official external website URL (e.g., https://www.institucion.com). Ensure to include https://
   */
  website?: string | null;
  /**
   * Uncheck to hide this institution from the public Next.js frontend.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions-media".
 */
export interface InstitutionsMedia {
  id: number;
  /**
   * Crucial for SEO and Accessibility. Describe the image content.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Auto-generated secure tracking identifier.
   */
  folio?: string | null;
  status?: ('new' | 'contacted' | 'scheduled' | 'completed' | 'cancelled') | null;
  /**
   * Internal notes for lead follow-up. Not visible to the patient.
   */
  contactNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Last manual response sent from the backend.
   */
  lastResponseSentAt?: string | null;
  name: string;
  email: string;
  phone: string;
  doctor: number | Doctor;
  procedure?: (number | null) | Procedure;
  notes?: string | null;
  /**
   * Choose the email template to send to the patient.
   */
  responseTemplate?: ('request_medical_records' | 'consultation_next_steps' | 'general_follow_up') | null;
  /**
   * Optional. Leave empty to use the template subject.
   */
  responseSubject?: string | null;
  /**
   * Optional custom message added to the selected template.
   */
  responseMessage?: string | null;
  /**
   * Check this box and save the lead to email the selected response to the patient.
   */
  sendResponseNow?: boolean | null;
  /**
   * Files uploaded by the patient through the secure folio link.
   */
  uploadedFiles?: (number | LeadFile)[] | null;
  /**
   * Audit trail for patient contact, file uploads and internal follow-up events.
   */
  communicationHistory?:
    | {
        direction: 'inbound' | 'outbound' | 'internal';
        eventType: 'lead_created' | 'email_sent' | 'email_failed' | 'file_uploaded' | 'internal_note';
        template?: string | null;
        subject?: string | null;
        message?: string | null;
        file?: (number | null) | LeadFile;
        occurredAt: string;
        createdBy?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-files".
 */
export interface LeadFile {
  id: number;
  lead: number | Lead;
  originalName: string;
  patientNote?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Media assets exclusively for global pages like the Patient Journey.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-assets".
 */
export interface MedicalAsset {
  id: number;
  /**
   * Crucial for SEO and Accessibility. Describe the image content.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'backend-roles';
        value: number | BackendRole;
      } | null)
    | ({
        relationTo: 'specialties';
        value: number | Specialty;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'facilities';
        value: number | Facility;
      } | null)
    | ({
        relationTo: 'institutions';
        value: number | Institution;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'lead-files';
        value: number | LeadFile;
      } | null)
    | ({
        relationTo: 'procedures';
        value: number | Procedure;
      } | null)
    | ({
        relationTo: 'doctors-media';
        value: number | DoctorsMedia;
      } | null)
    | ({
        relationTo: 'facilities-media';
        value: number | FacilitiesMedia;
      } | null)
    | ({
        relationTo: 'institutions-media';
        value: number | InstitutionsMedia;
      } | null)
    | ({
        relationTo: 'certificates-media';
        value: number | CertificatesMedia;
      } | null)
    | ({
        relationTo: 'procedures-media';
        value: number | ProceduresMedia;
      } | null)
    | ({
        relationTo: 'medical-assets';
        value: number | MedicalAsset;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  backendRoles?: T;
  fullName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backend-roles_select".
 */
export interface BackendRolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  isActive?: T;
  permissions?:
    | T
    | {
        target?: T;
        read?: T;
        create?: T;
        update?: T;
        delete?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialties_select".
 */
export interface SpecialtiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  medicalLicense?: T;
  profilePicture?: T;
  officeGallery?: T;
  specialties?: T;
  procedures?: T;
  facilities?: T;
  biography?: T;
  heroBackground?: T;
  heroVideoUrl?: T;
  procedureGallery?: T;
  procedureVideoLinks?:
    | T
    | {
        title?: T;
        url?: T;
        caption?: T;
        thumbnail?: T;
        id?: T;
      };
  patientTestimonials?:
    | T
    | {
        title?: T;
        videoUrl?: T;
        patientLocation?: T;
        quote?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  phone?: T;
  email?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  name?: T;
  issuer?: T;
  verificationUrl?: T;
  logo?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities_select".
 */
export interface FacilitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  city?: T;
  specialtiesOffered?: T;
  doctors?: T;
  accreditations?: T;
  heroImage?: T;
  heroVideoUrl?: T;
  infrastructureGallery?: T;
  infrastructureVideoLinks?:
    | T
    | {
        title?: T;
        url?: T;
        caption?: T;
        thumbnail?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions_select".
 */
export interface InstitutionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  website?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  folio?: T;
  status?: T;
  contactNotes?: T;
  lastResponseSentAt?: T;
  name?: T;
  email?: T;
  phone?: T;
  doctor?: T;
  procedure?: T;
  notes?: T;
  responseTemplate?: T;
  responseSubject?: T;
  responseMessage?: T;
  sendResponseNow?: T;
  uploadedFiles?: T;
  communicationHistory?:
    | T
    | {
        direction?: T;
        eventType?: T;
        template?: T;
        subject?: T;
        message?: T;
        file?: T;
        occurredAt?: T;
        createdBy?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-files_select".
 */
export interface LeadFilesSelect<T extends boolean = true> {
  lead?: T;
  originalName?: T;
  patientNote?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procedures_select".
 */
export interface ProceduresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  specialty?: T;
  coverImage?: T;
  shortSummary?: T;
  fullDescription?: T;
  pricing?:
    | T
    | {
        startingPriceUSD?: T;
        financingAvailable?: T;
      };
  recoveryTime?: T;
  surgeryDuration?: T;
  anesthesiaType?: T;
  procedureGallery?: T;
  procedureVideoLinks?:
    | T
    | {
        title?: T;
        url?: T;
        caption?: T;
        thumbnail?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors-media_select".
 */
export interface DoctorsMediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities-media_select".
 */
export interface FacilitiesMediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions-media_select".
 */
export interface InstitutionsMediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates-media_select".
 */
export interface CertificatesMediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procedures-media_select".
 */
export interface ProceduresMediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-assets_select".
 */
export interface MedicalAssetsSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The official name of the business. Used in SEO meta tags and footers.
   */
  companyName: string;
  contactEmail: string;
  /**
   * Backend notification email for new patient consultations. Falls back to Contact Email or ADMIN_NOTIFICATION_EMAIL.
   */
  leadNotificationEmail?: string | null;
  /**
   * Recommended format: +1 (555) 123-4567 for global Click-to-Call compatibility.
   */
  contactPhone: string;
  /**
   * Verified Resend sender address used for lead notifications and patient emails. Example: notifications@yourdomain.com.
   */
  transactionalEmailFromAddress?: string | null;
  /**
   * Sender display name for patient-facing emails.
   */
  transactionalEmailFromName?: string | null;
  address: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zipCode?: string | null;
    country: string;
  };
  /**
   * Main brand color (Buttons, active links).
   */
  primaryColor: string;
  /**
   * Secondary elements (Headers, footers, accents).
   */
  secondaryColor: string;
  /**
   * Call to Actions, highlight badges, alert icons.
   */
  accentColor: string;
  /**
   * Global application background color.
   */
  backgroundColor: string;
  /**
   * Default typography color for high contrast.
   */
  textColor: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-journey".
 */
export interface PatientJourney {
  id: number;
  heroTitle: string;
  heroDescription: string;
  heroCover: number | MedicalAsset;
  steps: {
    /**
     * e.g., "Arrival", "Surgery", "Recovery"
     */
    title: string;
    description: string;
    /**
     * e.g., "Day 1", "Days 2-4"
     */
    duration?: string | null;
    image?: (number | null) | MedicalAsset;
    /**
     * Optional: Add multiple choices for this step (e.g., different recovery cities or hotels).
     */
    options?:
      | {
          /**
           * e.g., "Recovery in Bernal"
           */
          title: string;
          description: string;
          image: number | MedicalAsset;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Overrides the default SEO title. Keep under 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Meta description for Google search results. Keep under 160 characters.
   */
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-queretaro".
 */
export interface WhyQueretaro {
  id: number;
  hero: {
    title: string;
    subtitle: string;
    mainImage: number | MedicalAsset;
  };
  content: {
    sections: {
      layout?: ('imageLeft' | 'imageRight') | null;
      /**
       * URL-friendly identifier for the sticky nav (e.g., "safety", "connectivity").
       */
      anchorSlug: string;
      title: string;
      /**
       * A punchy, aggressive subtitle to catch attention.
       */
      highlightSubtitle: string;
      content: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      };
      sectionImage: number | MedicalAsset;
      id?: string | null;
      blockName?: string | null;
      blockType: 'advantageSection';
    }[];
  };
  seo: {
    metaTitle: string;
    metaDescription: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  contactEmail?: T;
  leadNotificationEmail?: T;
  contactPhone?: T;
  transactionalEmailFromAddress?: T;
  transactionalEmailFromName?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        country?: T;
      };
  primaryColor?: T;
  secondaryColor?: T;
  accentColor?: T;
  backgroundColor?: T;
  textColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-journey_select".
 */
export interface PatientJourneySelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  heroCover?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        duration?: T;
        image?: T;
        options?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-queretaro_select".
 */
export interface WhyQueretaroSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        mainImage?: T;
      };
  content?:
    | T
    | {
        sections?:
          | T
          | {
              advantageSection?:
                | T
                | {
                    layout?: T;
                    anchorSlug?: T;
                    title?: T;
                    highlightSubtitle?: T;
                    content?: T;
                    sectionImage?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}